### ISSUE TITLE
good correction plugin, but can not send message to channels

### ISSUE THREAD

**Issue by yinflying** [johnson-christopher/apply_corrections#1]
I find the plugin could corrected msg,but can not send message to channel, I dont think it is a good idea to see the corrected string myself only... 

So I fork and modify the plugin .... 
[https://github.com/yinflying/apply_corrections](https://github.com/yinflying/apply_corrections)

**Comment by raugturi** [comment]
This plugin corrects everyone's messages this way, not just yours. That's why it shows it to you only instead of sending it to the whole channel. I imagine if you enable this in most channels you'll be banned pretty quickly. If that's really what you want it to do it might work better as a bot you can put in channels you own or op.

If you want something that re-sends *your* last message with the correction applied that seems like it should be a new plugin rather than a modification to this one.

**Comment by raugturi** [comment]
I also added some comments to  your code in case you do want to start turning it into a different plugin.

One more thing to add would be that your last two commits should probably be squashed into one. It's difficult to see the changes to a file side by side if you delete and then re-add it.

**Comment by yinflying** [comment]
@raugturi Thank you for your reply and suggestion ! I have modified the code and add a "valid_nick" option for controling the hehavior that " correcting everyone's messages".Not a good way , but reach the goal.

Maybe , is it more better to add a "vaild_channel" option ?  I have to consider if there is a bot in that channel ....

hmmm, I have to laught at my perfect English writing....
